channels:
- conda-forge
dependencies:
- python=3.10.10
- pip<=23.1
- pip:
  - mlflow
  - cloudpickle==2.2.1
  - psutil==5.9.5
  - scikit-learn==1.2.2
  - typing-extensions==4.5.0
name: power_generation
